services:
  visionxai-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: "${BASE_IMAGE}"  # Pass the BASE_IMAGE dynamically
    container_name: visionxai-api
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    volumes:
      - .:/app  # Mount the current directory to the container
    restart: always
