services:
  visionxai-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visionxai-api
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    volumes:
      # Mount the current directory to the container for development purposes
      - .:/app
    restart: always
